FROM ghcr.io/seungjin/leloi-linux-base:daily
# source: https://gitlab.com/fedora/bootc/base-images
# source: https://gitlab.com/fedora/bootc/base-images/-/blob/main/Containerfile?ref_type=heads

LABEL org.opencontainers.image.title="LeLoi Linux"
LABEL org.opencontainers.image.description="LeLoi Linux's bootc container image"
LABEL org.opencontainers.image.authors="Seungjin Kim <seungjin@duck.com>"
LABEL org.opencontainers.image.licenses=MIT
LABEL org.opencontainers.image.source="https://github.com/seungjin/leloi-linux"

# PREPARE PACKAGES
COPY --chmod=0644 ./rootfs/usr/local/share/bootc/packages-added /usr/local/share/bootc/packages-added
COPY --chmod=0644 ./rootfs/usr/local/share/bootc/packages-removed /usr/local/share/bootc/packages-removed
COPY --chmod=0644 ./rootfs/etc/yum.repos.d/* /etc/yum.repos.d/

# INSTALL REPOS
RUN dnf -y install dnf5-plugins

# INSTALL PACKAGES
RUN dnf -y group install workstation-product-environment
RUN dnf -y install initial-setup
RUN grep "^[^#;]" /usr/local/share/bootc/packages-added | grep -qE '^[A-Ea-e]' && grep "^[^#;]" /usr/local/share/bootc/packages-added | grep -E '^[A-Ea-e]' | xargs dnf -y install --allowerasing || echo "pass"
RUN grep "^[^#;]" /usr/local/share/bootc/packages-added | grep -qE '^[F-Jf-j]' && grep "^[^#;]" /usr/local/share/bootc/packages-added | grep -E '^[F-Jf-j]' | xargs dnf -y install --allowerasing || echo "pass"
RUN grep "^[^#;]" /usr/local/share/bootc/packages-added | grep -qE '^[K-Ok-o]' && grep "^[^#;]" /usr/local/share/bootc/packages-added | grep -E '^[K-Ok-o]' | xargs dnf -y install --allowerasing || echo "pass"
RUN grep "^[^#;]" /usr/local/share/bootc/packages-added | grep -qE '^[P-Tp-t]' && grep "^[^#;]" /usr/local/share/bootc/packages-added | grep -E '^[P-Tp-t]' | xargs dnf -y install --allowerasing || echo "pass"
RUN grep "^[^#;]" /usr/local/share/bootc/packages-added | grep -qE '^[U-Zu-z]' && grep "^[^#;]" /usr/local/share/bootc/packages-added | grep -E '^[U-Zu-z]' | xargs dnf -y install --allowerasing || echo "pass"
RUN grep "^[^#;]" /usr/local/share/bootc/packages-added | grep -qE '^[0-9]' && grep "^[^#;]" /usr/local/share/bootc/packages-added | grep -E '^[0-9]' | xargs dnf -y install --allowerasing || echo "pass"


# REMOVE PACKAGES
RUN cat /usr/local/share/bootc/packages-removed | grep "^[^#;]" | xargs dnf -y remove
RUN dnf -y autoremove
RUN dnf clean all

# CONFIGURATION
COPY --chmod=0755 ./rootfs/usr/local/bin/* /usr/local/bin/
COPY --chmod=0644 ./rootfs/etc/skel/leloi-bootc /etc/skel/.bashrc.d/leloi-bootc
COPY --chmod=0600 ./rootfs/usr/lib/ostree/auth.json /usr/lib/ostree/auth.json
COPY --chmod=0644 ./rootfs/etc/vconsole.conf /etc/vconsole.conf
COPY --chmod=0644 ./rootfs/etc/sudoers.d/seungjin /etc/sudoers.d/seungjin
COPY --chmod=0644 ./rootfs/usr/share/xsessions/leftwm.desktop /usr/share/xsessions/leftwm.desktop
COPY --chmod=0644 ./rootfs/usr/share/ibus/component/hangul.xml /usr/share/ibus/component/hangul.xml 

#RUN systemctl set-default graphical.target 
RUN ln -sf /usr/lib/systemd/system/graphical.target /etc/systemd/system/default.target

#RUN systemctl mask systemd-remount-fs.service
# Created symlink '/etc/systemd/system/systemd-remount-fs.service' → '/dev/null'.
RUN ln -sf /dev/null /etc/systemd/system/systemd-remount-fs.service 

##
#RUN systemctl mask packagekit.service
RUN ln -sf /dev/null /etc/systemd/system/packagekit.service

#RUN systemctl mask packagekit-offline-update.service
RUN ln -sf /dev/null /etc/systemd/system/packagekit-offline-update.service

## my binaries
COPY --chmod=755 ./bin/* /usr/local/bin/


# systemctl enable gdm 
RUN if [ "$(readlink /etc/systemd/system/display-manager.service 2>/dev/null)" != "/usr/lib/systemd/system/gdm.service" ]; then \
    ln -sf /usr/lib/systemd/system/gdm.service /etc/systemd/system/display-manager.service; \
  fi


# This does not work at Containerfile
RUN gsettings set org.gnome.software allow-updates false
# This does not work at Containerfile
RUN gsettings set org.gnome.desktop.input-sources xkb-options "['caps:ctrl_modifier']"

# CLEAN & CHECK
RUN find /var/log -type f ! -empty -delete
RUN bootc container lint
